TownUtilityBillSystemV2/Controllers/CalculatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TownUtilityBillSystemV2.Models.Calculator;
using TownUtilityBillSystemV2.Models.HelperMethods;
using TownUtilityBillSystemV2.Models.UtilityModels;
using TownUtilityBillSystemV2.Resources;
using static TownUtilityBillSystemV2.Models.InitialDB.InitialDBEnums;

namespace TownUtilityBillSystemV2.Controllers
{
	[Authorize]
	public class CalculatorController : Controller
	{
		public ActionResult ShowCalculatorOnLine()
		{
			var model = new CalculatorItemModel();

			model.AddUtilitiesToCalculatorItemModel();

			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult CalculateCharges(CalculatorItemModel inputModel)
		{
			var model = new CalculatorItemModel();

			model.AddUtilitiesToCalculatorItemModel();

			if (ModelState.IsValid)
			{
				if (inputModel.ElectricUsage == 0 && inputModel.WaterUsage == 0 && inputModel.HeatUsage == 0 && inputModel.GasUsage == 0)
				{
					ViewBag.ErrorMessage = Localization.YouMustEnterAtLeastOneUtilityUsage;

					return View("~/Views/Calculator/ShowCalculatorOnLine.cshtml", model);
				}
				
				model.CalculateCharges(inputModel);

				return View("~/Views/Calculator/ShowCharges.cshtml", model);
			}

			return View("~/Views/Calculator/ShowCalculatorOnLine.cshtml", model);
		}

		public JsonResult GetLocalizatedWordsForChart()
		{
			return Json(HelperMethod.GetLocalizatedWordsForChart(), JsonRequestBehavior.AllowGet);
		}
	}
}

TownUtilityBillSystemV2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TownUtilityBillSystemV2.Models.News;
using TownUtilityBillSystemV2.Models.UtilitySupplier;
using TownUtilityBillSystemV2.Resources;

namespace TownUtilityBillSystemV2.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			var model = new NewsModel();

			model.GetNewsTitlesForSlideShow();

			return View(model);
		}

		public ActionResult About()
		{
			ViewBag.Title = Localization.About;

			return View();
		}

		public ActionResult Contact()
		{
			UtilitySupplierModel utilitySupplierModel = new UtilitySupplierModel();

			ViewBag.Title = Localization.Contact;

			return View(utilitySupplierModel.UtilitySupplier);
		}

		public ActionResult News()
		{
			var model = new NewsModel();

			model.GetNewsTitlesForSlideShow();

			return View("~/Views/News/News.cshtml", model);
		}

		public ActionResult ShowSingleNews(int newsId)
		{
			var model = new NewsModel();

			model.GetSingleNews(newsId);

			return View("~/Views/News/ShowSingleNews.cshtml", model);
		}
	}
}

TownUtilityBillSystemV2/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TownUtilityBillSystemV2.Controllers
{
	[Authorize]
	public class StatisticController : Controller
    {
		// GET: Statistic
		public ActionResult ShowStatisticMenu()
		{
			return View();
		}
	}
}

TownUtilityBillSystemV2/Views/Home/About.cshtml
@using TownUtilityBillSystemV2.Resources

<h2>@Localization.About</h2>

<p>
	<span class="span-bold span-red">@Localization.TownUtilityBillSystem V2</span>
	<span>
		@Localization.AboutData_IsAWebAppThatHelps
	</span>
</p>
<p>
	<span>@Localization.AboutData_TheFirstRelease <b>@Localization.AboutData_FirstReleaseDate</b></span>
</p>
	

<p>
	<span class="span-bold span-red">
		@Localization.DongEnergy
	</span>
	<span>
		@Localization.AboutData_IsOneOfNorthernEurope
	</span>	
</p>

<p>
	<span>
		@Localization.AboutData_ChangeNameDate
	</span>
	<span class="span-bold span-red">
		@Localization.DongEnergy
	</span>
	<span>
		@Localization.AboutData_HasChangedNameTo
	</span>
	<span class="span-bold span-blue">
		@Localization.Orsted
	</span>
	<span>
		@Localization.AboutData_ChairmanСitation
	</span>
</p>

TownUtilityBillSystemV2/Views/Home/Contact.cshtml
@model TownUtilityBillSystemV2.Models.UtilitySupplier.UtilitySupplier
@using TownUtilityBillSystemV2.Resources

@{
//ViewBag.Title = "Contact";
}


<h2>@Localization.Contact</h2>

<address>
	<p2 class="span-red"><b> @Model.Name</b></p2><br />
	@Model.Address<br />
	@Model.Phone<br />
	@Model.Fax<br />
	<a href="https://@Model.Site.ToString()" target="_blank">@Model.Site</a><br />
	@Model.Email
</address>

<div>
	<div id="contactMapCanvas"></div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7oyKXdpaKqurqotVj7_bhl9V9_7B5cMQ&libraries=places"
		type="text/javascript"></script>
<script>
	var mapDiv = document.getElementById('contactMapCanvas');
    var address = "@Model.Address.ToString()";
    var mapBuildingZoom = 11;

    var geocoder = new google.maps.Geocoder();

    geocoder.geocode({
        "address": address
    }, function (results, status) {
       map = new google.maps.Map(mapDiv, {
            center: results[0].geometry.location,
            zoom: mapBuildingZoom,
            mapTypeId: google.maps.MapTypeId.ROADMAP,
       })
        marker = new google.maps.Marker({
            position: results[0].geometry.location,
            map: map,
            draggable: true
        });
        });
</script>

TownUtilityBillSystemV2/Views/Home/Index.cshtml
@using TownUtilityBillSystemV2.Resources
@model TownUtilityBillSystemV2.Models.News.NewsModel

@{
	ViewBag.Title = Localization.TownUtilityBillSystem;
}

@if (Request.IsAuthenticated)
	{
<div class=" jumbotron">
	<h3 class="header-bold">@Localization.ChooseNextFacility:</h3>

	<div class="row">
		<div class="col-md-6 margin-top-20">
			<a href="@Url.Action("ShowUtilities", "Utility")" class="btn btn-primary btn-large btn-block">
				<span class="glyphicon glyphicon-flash"></span> @Localization.Utilities
			</a>
			<a href="@Url.Action("ShowCustomerMenu", "Customer")" class="btn btn-primary btn-large btn-block">
				<span class=" glyphicon glyphicon-user"></span> @Localization.Customers
			</a>
			<a href="@Url.Action("ShowStatisticMenu", "Statistic")" class="btn btn-primary btn-large btn-block">
				<span class="glyphicon glyphicon-dashboard"></span> @Localization.Statistic
			</a>
		</div>
		<div class="col-md-6 margin-top-20">
			<a href="@Url.Action("ShowBills", "Bill")" class="btn btn-primary btn-large btn-block">
				<span class="glyphicon glyphicon-list-alt"></span> @Localization.Bills
			</a>
			<a href="@Url.Action("PayOnLineBill", "Bill")" class="btn btn-primary btn-large btn-block">
				<span class="glyphicon glyphicon-usd"></span> @Localization.PayOnLine
			</a>
			<a href="@Url.Action("ShowCalculatorOnLine", "Calculator")" class="btn btn-primary btn-large btn-block">
				<span class="glyphicon glyphicon-usd"></span> @Localization.CalculatorOnLine
			</a>
		</div>
	</div>
	@Html.Partial("~/Views/News/_NewsAllPartial.cshtml", Model)
</div>
}

else
{
<h2 class="header-bold">@Localization.TownUtilityBillSystem</h2>
<h3 class="header-bold">@Localization.PleaseLogInOrRegister</h3>
}