TownUtilityBillSystemV2/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TownUtilityBillSystemV2.Models.AddressModels;
using TownUtilityBillSystemV2.Models.Chart;
using TownUtilityBillSystemV2.Models.HelperMethods;
using TownUtilityBillSystemV2.Models.TemperatureModels;
using static TownUtilityBillSystemV2.Models.InitialDB.InitialDBEnums;

namespace TownUtilityBillSystemV2.Controllers
{
	[Authorize]
	public class ChartController : Controller
    {
		public ActionResult ShowTemperatureChart()
		{
			var model = new AddressModel();

			ViewBag.TownList = model.GetTowns();

			ViewBag.ImageIconPath = HelperMethod.GetTemperatureIconImage();

			return View();
		}

		public ActionResult GetTemperatureChartData(int? townId)
		{
			var model = new ChartModel();

			model.TemperaturesModel = model.GetTemperatureChartData(townId);

			return Json(model.TemperaturesModel, JsonRequestBehavior.AllowGet);
		}

		public JsonResult GetLocalizatedWordsTemperatureChartForFirstLoad()
		{
			return Json(HelperMethod.GetLocalizatedWordsTemperatureChartForFirstLoad(), JsonRequestBehavior.AllowGet);
		}
	}
}

TownUtilityBillSystemV2/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TownUtilityBillSystemV2.Controllers
{
	[Authorize]
	public class StatisticController : Controller
    {
		// GET: Statistic
		public ActionResult ShowStatisticMenu()
		{
			return View();
		}
	}
}

TownUtilityBillSystemV2/Views/Statistic/ShowStatisticMenu.cshtml
@using TownUtilityBillSystemV2.Resources
@{
	ViewBag.Title = "ShowStatisticMenu";
}

<div class="jumbotron">
	<h3 class="header-bold">@Localization.Statistic (@Localization.Usage.ToLower()):</h3>
	<div class="row">
		<div class="col-md-6">
			<a href="@Url.Action("ShowPrivateCustomers", "Customer")" class="btn btn-primary btn-large btn-block">
				<span class=" glyphicon glyphicon-user"></span> @Localization.PrivateCustomers @Localization.Usage.ToLower()
			</a>
			<a href="@Url.Action("ShowLegalCustomers", "Customer")" class="btn btn-primary btn-large btn-block">
				<span class=" glyphicon glyphicon-home"></span> @Localization.LegalCustomers @Localization.Usage.ToLower()
			</a>
			<hr />
			<a href="@Url.Action("ShowTemperatureChart", "Chart")" class="btn btn-primary btn-large btn-block">
				<span class=" glyphicon glyphicon-globe"></span>  @Localization.Temperature
			</a>
		</div>
	</div>
	<hr />
	@Html.Partial("~/Views/Shared/_BackToPreviousPagePartial.cshtml")
</div>